pool:
  vmImage: 'ubuntu-16.04'

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh
      rustup update stable
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      echo $(rustc --version)
    displayName: Install rust
  - script: cargo build --all
    displayName: Cargo build
  - script: cargo test --all
    displayName: Cargo unit test
  - script: cargo test --test server_test -- --ignored --nocapture
    displayName: Cargo integration test