pool:
  vmImage: 'ubuntu-16.04'

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh
      rustup install 1.37.0
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      echo $(rustc --version)
    displayName: Install rust
  - script: cargo build --all
    displayName: Cargo build
  - script: cargo test --all
    displayName: Cargo test