[package]
name = "reredis"
version = "0.1.0"
authors = ["huangjiahua <jiahua.h at outlook dot com>"]
edition = "2018"

[dependencies]
murmurhash64 = "0.3.1"
rand = "0.7.0"
chrono = "0.4.7"
mio = "0.6.19"
log = "0.4.0"
env_logger = "0.6.2"
jemallocator = "0.3.0"
jemalloc-sys = "0.3.2"
